clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 100

    # The number of clients selected in each round
    per_round: 20

    # Should the clients compute test accuracy locally?
    do_test: false

    comm_simulation: false

server:
    address: 127.0.0.1
    port: 8080

    # No client processes will be launched by the server
    disable_clients: true

    comm_simulation: false

    do_test: true

data:
    dataset_name: glue
    dataset_config: mrpc

    # Number of samples in each partition
    partition_size: 200
    # min_partition_size: 50
    # client_quantity_concentration: 0.3
    # label_concentration: 0.3
    # IID or non-IID?
    sampler: noniid
    concentration: 0.5
    partition_distribution:
        distribution: uniform
        low: 0.4
        high: 1.0

    # The random seed for sampling data
    random_seed: 42

trainer:
    # The type of the trainer
    type: HuggingFace

    # The maximum number of training rounds
    rounds: 500
    
    max_concurrency: 3

    # The target perplexity
    target_accuracy: 0.95

    # The machine learning model
    model_name: roberta-large
    model_type: huggingface

    # Number of epoches for local training in each communication round
    epochs: 3
    batch_size: 12
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0

    lora:
        r: 8
        lora_alpha: 16
        lora_dropout: 0.05
        bias: none
        task_type: SEQ_CLS
